export const AD_LIST_REQUEST = "AD_LIST_REQUEST";
export const AD_LIST_SUCCESS = "AD_LIST_SUCCESS";
export const AD_LIST_FAIL = "AD_LIST_FAIL";

export const AD_DELETE_REQUEST = "AD_DELETE_REQUEST";
export const AD_DELETE_SUCCESS = "AD_DELETE_SUCCESS";
export const AD_DELETE_FAIL = "AD_DELETE_FAIL";

export const AD_CREATE_REQUEST = "AD_CREATE_REQUEST";
export const AD_CREATE_SUCCESS = "AD_CREATE_SUCCESS";
export const AD_CREATE_FAIL = "AD_CREATE_FAIL";

export const AD_UPDATE_REQUEST = "AD_UPDATE_REQUEST";
export const AD_UPDATE_SUCCESS = "AD_UPDATE_SUCCESS";
export const AD_UPDATE_FAIL = "AD_UPDATE_FAIL";


export const SINGLE_AD_LIST_REQUEST = "SINGLE_AD_LIST_REQUEST";
export const SINGLE_AD_LIST_SUCCESS = "SINGLE_AD_LIST_SUCCESS";
export const SINGLE_AD_LIST_FAIL = "SINGLE_AD_LIST_FAIL";