export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";
export const FETCH_LOGOUT = "FETCH_LOGOUT";

export const CHAT_UPDATE_REQUEST = "CHAT_UPDATE_REQUEST";
export const CHAT_UPDATE_SUCCESS = "CHAT_UPDATE_SUCCESS";
export const CHAT_UPDATE_FAIL = "CHAT_UPDATE_FAIL";